version: "3"
services:
  go_fileserver:
    image: ahdrr/go_fileserver:2022_12_12
    container_name: go_file_server
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 16650:16650
    volumes:
      - ./goconf:/etc/goconf
      - ./basedir:/basedir
    networks:
        file_server_net:
           aliases:
              - file_api_server

  nginx_vue:
    image: ahdrr/nging_vue:2022_12_12
    container_name: nginx_vue
    volumes:
        - ./nginx_conf:/etc/nginx/conf.d
    ports:
      - 9000:80
    networks:
        file_server_net:

networks:
  file_server_net:
