FROM node:17.9.0-alpine as builder
WORKDIR /home
COPY . .
RUN set -x \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install cnpm -g \
    && cnpm install \
    && cnpm run build

FROM nginx:1.23.1-alpine
COPY --from=builder /home/dist /usr/share/nginx/html

