FROM node:12.22.12-buster as builder
WORKDIR /home
COPY . .
RUN set -x \
    && npm config set registry https://registry.npm.taobao.org \
    && npm install cnpm@7.1.0 -g \
    && cnpm install \
    && npm run build

FROM nginx:1.23.1-alpine
COPY --from=builder /home/dist /usr/share/nginx/html

