FROM  golang:alpine3.16 as builder

WORKDIR /go/release

COPY . .

RUN set -x \
    && go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go mod tidy \
    && CGO_ENABLED=1 \ 
    GOOS=linux GOARCH=amd64 \
    go build -o /go_file_server \
    -x -ldflags="-w -s" \
    main.go


FROM alpine:3.16 
RUN mkdir /etc/goconf \
   && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories \
   && apk add  --no-cache tzdata 
COPY --from=builder /go_file_server /
COPY ./config.yaml /etc/goconf
CMD ["/go_file_server","-c","/etc/goconf/config.yaml"]
