#日志位置
logfile: "/var/log/server.log"
#日志级别
loglevel: "debug"
#工作目录
basedir: "/basedir"
#可选debug调试模式，release生产模式
ginmode: "release" 
# 监听端口
port: "16650"
# api授权token,简化curl调用
token: "1312300"
#授权用户
users:
    -
        username: "aa"
        password: "1"
        #相对于basedir，如果/{{basedir}}/{{role}}目录不存在，服务启动时会自动创建
        role: '/'


